// Copyright 2017 Google Inc. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package error_prone

import (
	"strings"

	"android/soong/java/config"
)

func init() {
	// These values are set into build/soong/java/config/config.go so that soong doesn't have any
	// references to external/error_prone, which may not always exist.
	config.ErrorProneJavacJar = "external/error_prone/javac/javac-9+181-r4173-1.jar"
	config.ErrorProneJar = "external/error_prone/error_prone/error_prone_core-2.2.0-with-dependencies.jar"
	config.ErrorProneClasspath = strings.Join([]string{
		"external/error_prone/error_prone/error_prone_annotations-2.2.0.jar",
		"external/error_prone/checkerframework/dataflow-2.2.2.jar",
		"external/error_prone/checkerframework/javacutil-2.2.2.jar",
		"external/error_prone/jFormatString/jFormatString-3.0.0.jar",
	}, ":")

	// The checks that are fatal to the build.
	config.ErrorProneChecksError = strings.Join([]string{
		// Errorprone default severity ERROR
		"-Xep:AsyncCallableReturnsNull:ERROR",
		"-Xep:AsyncFunctionReturnsNull:ERROR",
		"-Xep:BundleDeserializationCast:ERROR",
		"-Xep:ChainingConstructorIgnoresParameter:ERROR",
		"-Xep:CheckReturnValue:ERROR",
		"-Xep:CollectionIncompatibleType:ERROR",
		"-Xep:ComparisonOutOfRange:ERROR",
		"-Xep:CompatibleWithAnnotationMisuse:ERROR",
		"-Xep:CompileTimeConstant:ERROR",
		"-Xep:DaggerProvidesNull:ERROR",
		"-Xep:DeadException:ERROR",
		"-Xep:DeadThread:ERROR",
		"-Xep:DoNotCall:ERROR",
		"-Xep:EqualsNaN:ERROR",
		"-Xep:ForOverride:ERROR",
		"-Xep:FunctionalInterfaceMethodChanged:ERROR",
		"-Xep:FuturesGetCheckedIllegalExceptionType:ERROR",
		"-Xep:GuiceAssistedInjectScoping:ERROR",
		"-Xep:GuiceAssistedParameters:ERROR",
		"-Xep:GuiceInjectOnFinalField:ERROR",
		"-Xep:Immutable:ERROR",
		"-Xep:ImmutableModification:ERROR",
		"-Xep:IncompatibleArgumentType:ERROR",
		"-Xep:IndexOfChar:ERROR",
		"-Xep:InfiniteRecursion:ERROR",
		"-Xep:InjectMoreThanOneScopeAnnotationOnClass:ERROR",
		"-Xep:InvalidPatternSyntax:ERROR",
		"-Xep:IsInstanceOfClass:ERROR",
		"-Xep:JUnit3TestNotRun:ERROR",
		"-Xep:JUnit4SetUpNotRun:ERROR",
		"-Xep:JUnit4TearDownNotRun:ERROR",
		"-Xep:JUnit4TestNotRun:ERROR",
		"-Xep:JUnitAssertSameCheck:ERROR",
		"-Xep:JavaxInjectOnAbstractMethod:ERROR",
		"-Xep:LiteByteStringUtf8:ERROR",
		"-Xep:LoopConditionChecker:ERROR",
		"-Xep:MockitoCast:ERROR",
		"-Xep:MockitoUsage:ERROR",
		"-Xep:MoreThanOneInjectableConstructor:ERROR",
		"-Xep:MustBeClosedChecker:ERROR",
		"-Xep:NonCanonicalStaticImport:ERROR",
		"-Xep:NonFinalCompileTimeConstant:ERROR",
		"-Xep:OptionalEquality:ERROR",
		"-Xep:OverlappingQualifierAndScopeAnnotation:ERROR",
		"-Xep:PackageInfo:ERROR",
		"-Xep:PreconditionsCheckNotNull:ERROR",
		"-Xep:PreconditionsCheckNotNullPrimitive:ERROR",
		"-Xep:ProtoFieldNullComparison:ERROR",
		"-Xep:ProvidesMethodOutsideOfModule:ERROR",
		"-Xep:RandomCast:ERROR",
		"-Xep:RestrictedApiChecker:ERROR",
		"-Xep:SelfAssignment:ERROR",
		"-Xep:StreamToString:ERROR",
		"-Xep:SuppressWarningsDeprecated:ERROR",
		"-Xep:ThrowIfUncheckedKnownChecked:ERROR",
		"-Xep:ThrowNull:ERROR",
		"-Xep:TruthSelfEquals:ERROR",
		"-Xep:TypeParameterQualifier:ERROR",
		"-Xep:UnnecessaryTypeArgument:ERROR",
		"-Xep:UnusedAnonymousClass:ERROR",
		// Errorprone default severity WARNING
		// Errorprone default severity SUGGESTION
	}, " ")

	// The checks that are not fatal to the build.
	config.ErrorProneChecksWarning = strings.Join([]string{
		// Errorprone default severity ERROR
		"-Xep:AndroidInjectionBeforeSuper:WARN",
		"-Xep:ArrayEquals:WARN",
		"-Xep:ArrayFillIncompatibleType:WARN",
		"-Xep:ArrayHashCode:WARN",
		"-Xep:ArrayToString:WARN",
		"-Xep:ArraysAsListPrimitiveArray:WARN",
		"-Xep:AutoValueConstructorOrderChecker:WARN",
		"-Xep:BadShiftAmount:WARN",
		"-Xep:ComparableType:WARN",
		"-Xep:ComplexBooleanConstant:WARN",
		"-Xep:ConditionalExpressionNumericPromotion:WARN",
		"-Xep:ConstantOverflow:WARN",
		"-Xep:EqualsReference:WARN",
		"-Xep:FormatString:WARN",
		"-Xep:FormatStringAnnotation:WARN",
		"-Xep:GetClassOnAnnotation:WARN",
		"-Xep:GetClassOnClass:WARN",
		"-Xep:GuardedBy:WARN",
		"-Xep:HashtableContains:WARN",
		"-Xep:IdentityBinaryExpression:WARN",
		"-Xep:InexactVarargsConditional:WARN",
		"-Xep:InvalidTimeZoneID:WARN",
		"-Xep:IsLoggableTagLength:WARN",
		"-Xep:JUnit4ClassAnnotationNonStatic:WARN",
		"-Xep:MislabeledAndroidString:WARN",
		"-Xep:MissingSuperCall:WARN",
		"-Xep:MisusedWeekYear:WARN",
		"-Xep:ModifyingCollectionWithItself:WARN",
		"-Xep:NCopiesOfChar:WARN",
		"-Xep:NonRuntimeAnnotation:WARN",
		"-Xep:NullTernary:WARN",
		"-Xep:OverridesJavaxInjectableMethod:WARN",
		"-Xep:PredicateIncompatibleType:WARN",
		"-Xep:PrivateSecurityContractProtoAccess:WARN",
		"-Xep:ProtocolBufferOrdinal:WARN",
		"-Xep:RandomModInteger:WARN",
		"-Xep:RectIntersectReturnValueIgnored:WARN",
		"-Xep:ReturnValueIgnored:WARN",
		"-Xep:SelfComparison:WARN",
		"-Xep:SelfEquals:WARN",
		"-Xep:ShouldHaveEvenArgs:WARN",
		"-Xep:SizeGreaterThanOrEqualsZero:WARN",
		"-Xep:StreamResourceLeak:WARN",
		"-Xep:StringBuilderInitWithChar:WARN",
		"-Xep:TryFailThrowable:WARN",
		"-Xep:UnusedCollectionModifiedInPlace:WARN",

		// Errorprone default severity WARNING
		// "-Xep:AmbiguousMethodReference:WARN",
		// "-Xep:ArgumentSelectionDefectChecker:WARN",
		// "-Xep:AssertEqualsArgumentOrderChecker:WARN",
		// "-Xep:AssertionFailureIgnored:WARN",
		// "-Xep:BadAnnotationImplementation:WARN",
		// "-Xep:BadComparable:WARN",
		// "-Xep:BoxedPrimitiveConstructor:WARN",
		// "-Xep:CannotMockFinalClass:WARN",
		// "-Xep:CanonicalDuration:WARN",
		// "-Xep:CatchFail:WARN",
		// "-Xep:ClassCanBeStatic:WARN",
		// "-Xep:ClassNewInstance:WARN",
		// "-Xep:CollectionToArraySafeParameter:WARN",
		// "-Xep:CollectorShouldNotUseState:WARN",
		// "-Xep:ComparableAndComparator:WARN",
		// "-Xep:DateFormatConstant:WARN",
		// "-Xep:DefaultCharset:WARN",
		// "-Xep:DoubleCheckedLocking:WARN",
		// "-Xep:EqualsHashCode:WARN",
		// "-Xep:EqualsIncompatibleType:WARN",
		// "-Xep:FallThrough:WARN",
		// "-Xep:Finally:WARN",
		// "-Xep:FloatCast:WARN",
		// "-Xep:FloatingPointLiteralPrecision:WARN",
		// "-Xep:FragmentInjection:WARN",
		// "-Xep:FragmentNotInstantiable:WARN",
		// "-Xep:FutureReturnValueIgnored:WARN",
		// "-Xep:GetClassOnEnum:WARN",
		// "-Xep:HidingField:WARN",
		// "-Xep:ImmutableAnnotationChecker:WARN",
		// "-Xep:ImmutableEnumChecker:WARN",
		// "-Xep:IncompatibleModifiers:WARN",
		// "-Xep:IncrementInForLoopAndHeader:WARN",
		// "-Xep:InjectOnConstructorOfAbstractClass:WARN",
		// "-Xep:InputStreamSlowMultibyteRead:WARN",
		// "-Xep:InstanceOfAndCastMatchWrongType:WARN",
		// "-Xep:IntLongMath:WARN",
		// "-Xep:IterableAndIterator:WARN",
		// "-Xep:JUnit3FloatingPointComparisonWithoutDelta:WARN",
		// "-Xep:JUnit4ClassUsedInJUnit3:WARN",
		// "-Xep:JUnitAmbiguousTestClass:WARN",
		// "-Xep:JavaLangClash:WARN",
		// "-Xep:JdkObsolete:WARN",
		// "-Xep:LogicalAssignment:WARN",
		// "-Xep:MissingCasesInEnumSwitch:WARN",
		// "-Xep:MissingFail:WARN",
		// "-Xep:MissingOverride:WARN",
		// "-Xep:ModifyCollectionInEnhancedForLoop:WARN",
		// "-Xep:MultipleParallelOrSequentialCalls:WARN",
		// "-Xep:MutableConstantField:WARN",
		// "-Xep:NamedParameters:WARN",
		// "-Xep:NarrowingCompoundAssignment:WARN",
		// "-Xep:NestedInstanceOfConditions:WARN",
		// "-Xep:NonAtomicVolatileUpdate:WARN",
		// "-Xep:NonOverridingEquals:WARN",
		// "-Xep:NullableConstructor:WARN",
		// "-Xep:NullablePrimitive:WARN",
		// "-Xep:NullableVoid:WARN",
		// "-Xep:OperatorPrecedence:WARN",
		// "-Xep:OptionalNotPresent:WARN",
		// "-Xep:OverrideThrowableToString:WARN",
		// "-Xep:Overrides:WARN",
		// "-Xep:OverridesGuiceInjectableMethod:WARN",
		// "-Xep:ParameterName:WARN",
		// "-Xep:PreconditionsInvalidPlaceholder:WARN",
		// "-Xep:ProtoFieldPreconditionsCheckNotNull:WARN",
		// "-Xep:ReachabilityFenceUsage:WARN",
		// "-Xep:ReferenceEquality:WARN",
		// "-Xep:RequiredModifiers:WARN",
		// "-Xep:ShortCircuitBoolean:WARN",
		// "-Xep:StaticGuardedByInstance:WARN",
		// "-Xep:StringSplitter:WARN",
		// "-Xep:SynchronizeOnNonFinalField:WARN",
		// "-Xep:ThreadJoinLoop:WARN",
		// "-Xep:ThreadLocalUsage:WARN",
		// "-Xep:ThreeLetterTimeZoneID:WARN",
		// "-Xep:TruthConstantAsserts:WARN",
		// "-Xep:TypeParameterShadowing:WARN",
		// "-Xep:TypeParameterUnusedInFormals:WARN",
		// "-Xep:URLEqualsHashCode:WARN",
		// "-Xep:UnsafeFinalization:WARN",
		// "-Xep:UnsynchronizedOverridesSynchronized:WARN",
		// "-Xep:UseCorrectAssertInTests:WARN",
		// "-Xep:WaitNotInLoop:WARN",
		// "-Xep:WakelockReleasedDangerously:WARN",

		// Errorprone default severity SUGGESTION
	}, " ")

	// The checks that are default-disabled and listed for completeness
	// and simple experiments.
	config.ErrorProneChecksDefaultDisabled = strings.Join([]string{
		// Errorprone default severity ERROR
		// "-Xep:AssistedInjectAndInjectOnSameConstructor:ERROR",
		// "-Xep:AutoFactoryAtInject:ERROR",
		// "-Xep:ClassName:ERROR",
		// "-Xep:ComparisonContractViolated:ERROR",
		// "-Xep:DepAnn:ERROR",
		// "-Xep:DivZero:ERROR",
		// "-Xep:EmptyIf:ERROR",
		// "-Xep:FuzzyEqualsShouldNotBeUsedInEqualsMethod:ERROR",
		// "-Xep:InjectInvalidTargetingOnScopingAnnotation:ERROR",
		// "-Xep:InjectMoreThanOneQualifier:ERROR",
		// "-Xep:InjectScopeAnnotationOnInterfaceOrAbstractClass:ERROR",
		// "-Xep:InjectScopeOrQualifierAnnotationRetention:ERROR",
		// "-Xep:InjectedConstructorAnnotations:ERROR",
		// "-Xep:InsecureCryptoUsage:ERROR",
		// "-Xep:IterablePathParameter:ERROR",
		// "-Xep:JMockTestWithoutRunWithOrRuleAnnotation:ERROR",
		// "-Xep:JavaxInjectOnFinalField:ERROR",
		// "-Xep:LockMethodChecker:ERROR",
		// "-Xep:LongLiteralLowerCaseSuffix:ERROR",
		// "-Xep:NoAllocation:ERROR",
		// "-Xep:NumericEquality:ERROR",
		// "-Xep:ParameterPackage:ERROR",
		// "-Xep:ProtoStringFieldReferenceEquality:ERROR",
		// "-Xep:QualifierOrScopeOnInjectMethod:ERROR",
		// "-Xep:RestrictTo:ERROR",
		// "-Xep:StaticOrDefaultInterfaceMethod:ERROR",
		// "-Xep:UnlockMethod:ERROR",

		// Errorprone default severity WARNING
		// "-Xep:AssertFalse:WARN",
		// "-Xep:AssistedInjectAndInjectOnConstructors:WARN",
		// "-Xep:BigDecimalLiteralDouble:WARN",
		// "-Xep:BinderIdentityRestoredDangerously:WARN",
		// "-Xep:BindingToUnqualifiedCommonType:WARN",
		// "-Xep:ConstructorInvokesOverridable:WARN",
		// "-Xep:ConstructorLeaksThis:WARN",
		// "-Xep:EmptyTopLevelDeclaration:WARN",
		// "-Xep:ExpectedExceptionChecker:WARN",
		// "-Xep:FunctionalInterfaceClash:WARN",
		// "-Xep:HardCodedSdCardPath:WARN",
		// "-Xep:InconsistentOverloads:WARN",
		// "-Xep:MissingDefault:WARN",
		// "-Xep:MutableMethodReturnType:WARN",
		// "-Xep:NonCanonicalStaticMemberImport:WARN",
		// "-Xep:PrimitiveArrayPassedToVarargsMethod:WARN",
		// "-Xep:ProvidesFix:WARN",
		// "-Xep:QualifierWithTypeUse:WARN",
		// "-Xep:RedundantThrows:WARN",
		// "-Xep:StaticQualifiedUsingExpression:WARN",
		// "-Xep:StringEquality:WARN",
		// "-Xep:StringSplit:WARN",
		// "-Xep:TestExceptionChecker:WARN",
		// "-Xep:UnnecessaryDefaultInEnumSwitch:WARN",
		// "-Xep:Var:WARN",

		// Errorprone default severity SUGGESTION
		// "-Xep:BooleanParameter:SUGGESTION",
		// "-Xep:ConstantField:SUGGESTION",
		// "-Xep:EmptySetMultibindingContributions:SUGGESTION",
		// "-Xep:FieldMissingNullable:SUGGESTION",
		// "-Xep:LambdaFunctionalInterface:SUGGESTION",
		// "-Xep:MethodCanBeStatic:SUGGESTION",
		// "-Xep:MixedArrayDimensions:SUGGESTION",
		// "-Xep:MultiVariableDeclaration:SUGGESTION",
		// "-Xep:MultipleTopLevelClasses:SUGGESTION",
		// "-Xep:MultipleUnaryOperatorsInMethodCall:SUGGESTION",
		// "-Xep:PackageLocation:SUGGESTION",
		// "-Xep:ParameterComment:SUGGESTION",
		// "-Xep:ParameterNotNullable:SUGGESTION",
		// "-Xep:PrivateConstructorForNoninstantiableModuleTest:SUGGESTION",
		// "-Xep:PrivateConstructorForUtilityClass:SUGGESTION",
		// "-Xep:RemoveUnusedImports:SUGGESTION",
		// "-Xep:ReturnMissingNullable:SUGGESTION",
		// "-Xep:SwitchDefault:SUGGESTION",
		// "-Xep:ThrowsUncheckedException:SUGGESTION",
		// "-Xep:TypeParameterNaming:SUGGESTION",
		// "-Xep:UngroupedOverloads:SUGGESTION",
		// "-Xep:UnnecessarySetDefault:SUGGESTION",
		// "-Xep:UnnecessaryStaticImport:SUGGESTION",
		// "-Xep:UseBinds:SUGGESTION",
		// "-Xep:WildcardImport:SUGGESTION",
	}, " ")

	config.ErrorProneFlags = strings.Join([]string{
		"com.google.errorprone.ErrorProneCompiler",
		"-Xdiags:verbose",
		"-XDcompilePolicy=simple",
		"-XDallowBetterNullChecks=false",
		"-XDusePolyAttribution=true",
		"-XDuseStrictMethodClashCheck=true",
		"-XDuseStructuralMostSpecificResolution=true",
		"-XDuseGraphInference=true",
		"-XDandroidCompatible=true",
		// We are not interested in Guava recommendations
		// for String.split.
		"-Xep:StringSplitter:OFF",
		"-Xmaxwarns 9999999",  // As we emit errors as warnings,
		                       // increase the warning limit.
	}, " ")
}
